### PR TITLE
Turn the NumLock key into a macro

### PR DESCRIPTION
**Pull request by algernon**
Instead of just switching to a layer, make it a macro. The macro will toggle the layer and the LED effect.

Depends on keyboardio/Keyboardio-Macros#1 and keyboardio/Keyboardio-LEDEffect-Numlock#2.

Appears to work fine after a quick test.

### CODE REVIEW

**Comment by algernon** [comment]
The Travis failure is expected, because the PRs this one depends on aren't merged.

**Comment by algernon** [comment]
Something like `NumLockMacro`?

**Comment by obra** [comment]
ToggleNumlock?

**Comment by algernon** [comment]
Sounds good. I'll amend this, and keyboardio/Keyboardio-LEDEffect-Numlock#2 too ~tomorrow.

**Comment by algernon** [comment]
Closing & reopening to trigger a new travis build...

**Pull request merged**
