### PR TITLE
A way to assign complex sequences to a single key

### PR DESCRIPTION
**Pull request by algernon**
This patchset does a number of things:

- It moves all the macro stuff into a separate library, with its own event handler hook.
- Provides a `macroAction` function that can be overridden from the Sketch.
- Implements a player for a simple sequence of actions `macroAction` can return.

These combined make it possible to assign an arbitrary long sequence to a single key, and all kinds of keys can be used, even other macros. At the same time, the `macroAction` callback can do any side effects it wants, or even skip the whole "return a macro" thing, and return `MACRO_NONE`, and do everything itself.

I am not 100% sure about the `Keyboard.sendReport()` calls, mind you, that would need some testing on real hardware, not just in my head.

### CODE REVIEW

**Comment by obra** [comment]
sendReport looks right from a quick first glance. The theory is that you
want to do that every time you get the report into a consistent state.

If you throw together an example sketch, I can test it on real hardware.

Is there any chance we could figure out a way to not force macros into
numbered slots somewhere down the line and instead let people name them?
It may make it easier for users to share macros.

**Comment by algernon** [comment]
There is an example in the default Sketch, though it is not bound to anything. I'll build a testable one too, that also shows how you can name your macros (enums!).

**Comment by algernon** [comment]
[Sketch here](https://gist.github.com/algernon/57974ec23d49172d5f2cc3e8734ab30a). It's the same layout as the default one, except it's self-contained, and has a macro on the outer top corner of each half. The left one prints to Serial, and returns a macro that types `Model 01`, the right one plays with the LEDs, and does not do anything with keys.

The Sketch also shows how to "name" macros or layers, when not using the generator.

**Comment by obra** [comment]
Testing this on hardware, it seems like the "key release" macro step doesn't work. So the sample macro generates "MODEL )!" rather than "Model 01"

This makes some sense because of the way the core firmware handles key reports. We never really generate a release event, we simply don't add a pressed key to the report we're sending.

Because the macro system as currently written doesn't create a fresh report at each step, there's nothing to clear the bit in the report.

Possible solutions include adding explicit "clear this bit" support in the report and having the macro system handle its own reports a bit more directly.

**Comment by algernon** [comment]
Right. I originally used `Keyboard.press` and `Keyboard.release` directly, which didn't have this problem. I'd go with the explicit "clear this bit" support. Perhaps a flag like `INJECT`? Could call it `FORCE_RELEASE`, perhaps.

**Comment by algernon** [comment]
Suggestion: I'll add a `release_key` function, similar to `press_key`, that the default handler would call when the key is to be released **and** the `FORCE_RELEASE` bit is set on the `keyState`. Then the `U()` macro would add that bit.

**Comment by algernon** [comment]
PR updated. In the end, I did not introduce a `FORCE_RELEASE` flag, but reused `INJECT`: a toggled off, injected key event will now trigger `release_key` that does the opposite of `press_key`.

This should hopefully fix the macros.

**Pull request merged**
